server:
  port: 8081
  #  servlet:
  #    context-path: /api/v1
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  security:
    basic:
      enable: false

app:
  rabbitmq:
    exchange: exchange
    cocinaQueue: CocinaQueue
    barQueue: BarQueue
    compraQueue: CompraQueue
    cocinaKey: cocina_key
    barKey: bar_key
    compraKey: compra_key
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 36000000 # 1 hour = 3600000, 1 minuto = 60000
    tokenRefreshExpirationMsec: 360000000 # around 4.1 days.
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect