
-- create tables for menu
CREATE TABLE public.item_menu (
	item_menu_id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	receta_id int8 NOT NULL,
	nombre_comercial varchar NOT NULL,
	descripcion varchar NOT NULL,
	precio_venta float8 NOT NULL,
	CONSTRAINT item_menu_pk PRIMARY KEY (item_menu_id),
	CONSTRAINT item_menu_recetas_fk FOREIGN KEY (receta_id) REFERENCES public.recetas(id)
);
CREATE TABLE public.menu (
	id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	nombre varchar NOT NULL,
	temporada varchar NOT NULL,
	descripcion varchar NOT NULL,
	usu_registra int8 NOT NULL,
	fecha_registro date NOT NULL,
	usu_modifica int8 NULL,
	fecha_modifica date NULL,
	estado int DEFAULT 1 NOT NULL,
	CONSTRAINT menu_pk PRIMARY KEY (id),
	CONSTRAINT menu_usuario_fk FOREIGN KEY (usu_registra) REFERENCES public.usuario(id),
	CONSTRAINT menu_usuario_fk_1 FOREIGN KEY (usu_modifica) REFERENCES public.usuario(id)
);
CREATE TABLE public.seccion_menu (
	seccion_id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	nombre varchar NOT NULL,
	menu_id int8 NOT NULL,
	CONSTRAINT seccion_menu_pk PRIMARY KEY (seccion_id),
	CONSTRAINT seccion_menu_menu_fk FOREIGN KEY (menu_id) REFERENCES public.menu(id)
);
CREATE TABLE public.secciones_item_menu (
	seccion_id int8 NOT NULL,
	item_id int8 NOT NULL,
	CONSTRAINT secciones_item_menu_item_menu_fk FOREIGN KEY (item_id) REFERENCES public.item_menu(item_menu_id),
	CONSTRAINT secciones_item_menu_seccion_menu_fk FOREIGN KEY (seccion_id) REFERENCES public.seccion_menu(seccion_id)
);