# CircleCI configuration file
#version: 2.1
#orbs:
#  maven: circleci/maven@1.1
#workflows:
#  maven_test:
#    jobs:
#      - maven/install

version: 2.1

executors:
  build-pod:
    docker:
      - image: cimg/openjdk:17.0.10
    working_directory: /workspace

parameters:
  dockerImageNameAdmin:
    description: Name of the Admin image
    type: string
    default: "pvgourmet/pura-vida-gourmet-admin"
  dockerImageNameRestaurante:
    description: Name of the Restaurante image
    type: string
    default: "pvgourmet/pura-vida-gourmet-restaurante"
  dockerImageNameEngine:
    description: Name of the Engine image
    type: string
    default: "pvgourmet/pura-vida-gourmet-engine"
  dockerImageVersion:
    description: version of the docker image
    type: string
    default: "1.2"

jobs:
  buildAndDeploy:
    working_directory: ~/project
    executor: build-pod
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          name: Maven Clean Install
          command: mvn clean install
      - when:
          condition:
            equal: [ master, <<pipeline.git.branch>> ]
          steps:
            - run:
                name: Build Docker Admin Image
                command: docker build -t <<pipeline.parameters.dockerImageNameAdmin>>:<<pipeline.parameters.dockerImageVersion>> admin/.
            - run:
                name: Build Docker Restaurante Image
                command: docker build -t <<pipeline.parameters.dockerImageNameRestaurante>>:<<pipeline.parameters.dockerImageVersion>> engines/.
            - run:
                name: Build Docker Engine Image
                command: docker build -t <<pipeline.parameters.dockerImageNameEngine>>:<<pipeline.parameters.dockerImageVersion>> engines/.
            - run:
                name: Login
                command: echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            - run:
                name: Push Admin Image
                command: docker push <<pipeline.parameters.dockerImageNameAdmin>>:<<pipeline.parameters.dockerImageVersion>>
            - run:
                name: Push Restaurante Image
                command: docker push <<pipeline.parameters.dockerImageNameRestaurante>>:<<pipeline.parameters.dockerImageVersion>>
            - run:
                name: Push Engine Image
                command: docker push <<pipeline.parameters.dockerImageNameEngine>>:<<pipeline.parameters.dockerImageVersion>>
      - run: echo "No Docker Image creation or deployment needed."

workflows:
  build:
    jobs:
      - buildAndDeploy
