# CircleCI configuration file
#version: 2.1
#orbs:
#  maven: circleci/maven@1.1
#workflows:
#  maven_test:
#    jobs:
#      - maven/install

version: 2.1

parameters:
  dockerImageName:
    description: name of the docker image
    type: string
    default: "pvgourmet/pura-vida-gourmet"
  dockerImageVersion:
    description: version of the docker image
    type: string
    default: "1.1"

jobs:
  setup:
    working_directory: ~/project
    docker:
      - image: cimg/openjdk:17.0.10
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
  build:
    working_directory: ~/project
    docker:
      - image: cimg/openjdk:17.0.10
    steps:
      - checkout
      - run:
          name: Maven Clean Install
          command: mvn clean install
  buildImageAndDeploy:
    working_directory: ~/project
    docker:
      - image: cimg/openjdk:17.0.10
    steps:
      - when:
          condition:
            equal: [ master, <<pipeline.git.branch>> ]
          steps:
            - run:
                name: Build Docker Image
                command: docker build -t <<pipeline.parameters.dockerImageName>>:<<pipeline.parameters.dockerImageVersion>> .
            - run:
                name: Login
                command: echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            - run:
                name: Push Image
                command: docker push pvgourmet/<<pipeline.parameters.dockerImageName>>:<<pipeline.parameters.dockerImageVersion>>
      - run: echo "No Docker Image creation or deployment needed."

#workflows:
#  build:
#    jobs:
#      - setup
#      - build:
#          requires:
#            - setup
#      - buildImageAndDeploy:
#          requires:
#            - build