# CircleCI configuration file
#version: 2.1
#orbs:
#  maven: circleci/maven@1.1
#workflows:
#  maven_test:
#    jobs:
#      - maven/install

version: 2.1
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: cimg/openjdk:17.0.10
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          name: Maven Clean Install
          command: mvn clean install
      - run:
          name: Build Docker Image
          command: docker build -t pvgourmet/pura-vida-gourmet:1.1 .
      - run:
          name: Login
          command: echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
      - run:
          name: Push Image
          command: docker push pvgourmet/pura-vida-gourmet:1.1