# CircleCI configuration file
#version: 2.1
#orbs:
#  maven: circleci/maven@1.1
#workflows:
#  maven_test:
#    jobs:
#      - maven/install

version: 2.1

executors:
  build-pod:
    docker:
      - image: cimg/openjdk:17.0.10
    working_directory: /workspace

parameters:
  dockerImageName:
    description: name of the docker image
    type: string
    default: "pvgourmet/pura-vida-gourmet"
  dockerImageVersion:
    description: version of the docker image
    type: string
    default: "1.1"

jobs:
  buildAndDeploy:
    working_directory: ~/project
    executor: build-pod
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          name: Maven Clean Install
          command: mvn clean install
      - when:
          condition:
            equal: [ master, <<pipeline.git.branch>> ]
          steps:
            - run:
                name: Build Docker Image
                command: docker build -t <<pipeline.parameters.dockerImageName>>:<<pipeline.parameters.dockerImageVersion>> .
            - run:
                name: Login
                command: echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            - run:
                name: Push Image
                command: docker push <<pipeline.parameters.dockerImageName>>:<<pipeline.parameters.dockerImageVersion>>
      - run: echo "No Docker Image creation or deployment needed."

workflows:
  build:
    jobs:
      - buildAndDeploy
