# CircleCI configuration file
#version: 2.1
#orbs:
#  maven: circleci/maven@1.1
#workflows:
#  maven_test:
#    jobs:
#      - maven/install

version: 2.1
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/openjdk:11-jdk-buster
    steps:
      - checkout
      - run: mvn clean install
          #      - run:
          #          name: Build Docker Image
          #          command: |
          #            docker build \
          #              --tag pura-vida-gourmet:latest 
          .
#      - run:
#          name: Login to Docker Registry
#          command: |
#            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
#      - run:
#          name: Push Docker Image
#          command: |
#            docker tag my-image:latest my-registry/my-image:latest
#            docker push my-registry/my-image:latest