# CircleCI configuration file
#version: 2.1
#orbs:
#  maven: circleci/maven@1.1
#workflows:
#  maven_test:
#    jobs:
#      - maven/install

version: 2.1
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: cimg/openjdk:8.0.402
    steps:
      - checkout
      - run: mvn clean install
      - run:
          name: Build Docker Image
          command: docker build -t pvgourmet/pura-vida-gourment:1.1 .