version: '3.1'
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: gourmet
      POSTGRES_USER: puravida
      POSTGRES_DB: puraVida
    ports:
      - "5432:5432"
  rabbitmq:
    image: 'rabbitmq:3.13-management-alpine'
    ports:
      # The standard AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
    environment:
      # The location of the RabbitMQ server.  "amqp" is the protocol;
      # "rabbitmq" is the hostname.  Note that there is not a guarantee
      # that the server will start first!  Telling the pika client library
      # to try multiple times gets around this ordering issue.
      AMQP_URL: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
  app:
    image: pvgourmet/pura-vida-gourmet-api:1.2
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - db