version: '3.1'
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: gourmet
      POSTGRES_USER: puravida
      POSTGRES_DB: puraVida
    ports:
      - "5433:5432"
  app:
    image: pvgourmet/pura-vida-gourmet:1.1
    restart: on-failure
    ports:
      - "8081:8080"
    depends_on:
      - db